Repository zstenger93/Transcendence, pull requests merged in 2024-01, with the labels that each got.

#225 I had one job
  frontend/src/pages/Games/OriginalPong.js
Labels: you had one job

#236 bars response time fixed here as well
  frontend/src/pages/Games/OriginalPong.js
Labels: fixed, done

#237 bar responsiveness fixed here as well
  frontend/src/pages/Games/Pong3D.js
Labels: fixed

#238 Frontend
  frontend/src/App.js
  frontend/src/components/home/FadeIn.js
  frontend/src/components/home/Readme.js
  frontend/src/components/home/WelcomeMessage.js
  frontend/src/components/sidebar/Sidebar_Monitor.js
  frontend/src/images/sudo_transcEND.png
  frontend/src/pages/Home.js
  frontend/src/styles/tailwind.css
  frontend/tailwind.config.js
Labels: enhancement

#252 missing lines in nginx.sh
  docker/nginx/nginx.sh
Labels: fixed
